package com.example.visiontranslator.infra.model.translation

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.Query
import androidx.room.Update

@Dao
interface TranslationDao {
    /**
     * 新規Translationモデルを保存
     * @return autoGeneratedID
     */
    @Insert
    suspend fun insertTranslation(translation: Translation): Long

    /**
     * Translationモデルをアップデート
     */
    @Update
    suspend fun updateTranslation(translation: Translation)

    /**
     * 1つのTranslationモデルを削除
     */
    @Query("DELETE FROM translations WHERE id =:id")
    suspend fun deleteTranslationByID(id: Int)

    /**
     * すべてのTranslationsモデル削除
     */
    @Query("DELETE FROM translations")
    suspend fun deleteTranslations()

    /**
     * IDからTranslationモデル取得
     */
    @Query("SELECT * FROM translations WHERE id =:id")
    suspend fun getTranslationByID(id: Int): Translation?

    /**
     * すべてのTranslationを取得
     */
    @Query("SELECT * FROM translations")
    suspend fun getTranslations(): List<Translation>
}