package com.example.visiontranslator.infra.model.translation

import androidx.room.*

/**
 * 翻訳データを保持するTranslationモデルを操作するDAOメソッド
 */
@Dao
interface TranslationDao {

    /**
     * すべてのTranslationをリストとして取得
     */
    @Query("SELECT * FROM translations")
    suspend fun getAllTranslations(): List<Translation>

    /**
     * 新規Translationモデルを保存
     * @return autoGeneratedID
     */
    @Insert
    suspend fun insertTranslation(translation: Translation): Long

    /**
     * Translationモデルをアップデート
     */
    @Update
    suspend fun updateTranslation(translation: Translation)

    /**
     * 1つのTranslationモデルを削除
     */
    @Query("DELETE FROM translations WHERE id =:id")
    suspend fun deleteTranslationByID(id: Long)

    /**
     * すべてのTranslationsモデル削除
     */
    @Query("DELETE FROM translations")
    suspend fun deleteAllTranslations()

    /**
     * 複数のTranslationをトランザクションで削除
     */
    @Transaction
    suspend fun deleteTranslations(idList: List<Long>) {
        idList.map { deleteTranslationByID(it) }
    }

    /**
     * IDからTranslationモデル取得
     */
    @Query("SELECT * FROM translations WHERE id =:id")
    suspend fun findTranslationByID(id: Long): Translation?

    /**
     * クエリワードから検索しリストとして検索結果を返す
     */
    @Query("SELECT * FROM translations WHERE translated_text LIKE '%' || :queryWord || '%' OR original_text LIKE '%' || :queryWord || '%'")
    suspend fun findTranslationByQueryWord(queryWord: String) : List<Translation>
}